ryanSN/doxie-node

.gitignore
__tests__/index.spec.js
jest.config.js
lib/index.js
package.json
yarn.lock

Add Axios, add some tests and file streaming tests.

feat: add tests use axios over fetch

---

.travis.yml
package.json

feat: add travis CI

---

README.md

Add Travis CI badge to readme.

chore: add Travis CI badge

---

README.md

Add some development details to the readme.

chore: some readme updates

---

README.md
__tests__/index.spec.js
lib/index.js
lib/retry.js
package.json
yarn.lock

feat: retry

---

README.md
package.json
yarn.lock

feat: Readme updates

---

README.md
__tests__/index.spec.js
lib/index.js
lib/retryPromise.js

- up code cov
- remove the bail logic that probably won't be used. (Add back in when thought out more).
- fix spots in readme

chore: code cov readme updates

---

package.json
yarn.lock

Greenkeeper/rollup 1.9.0

---

package.json
yarn.lock

Greenkeeper/lint staged 8.1.5

---

package.json
yarn.lock

- Address Axios security vuln:
https://nvd.nist.gov/vuln/detail/CVE-2019-10742

security(axios): version bump

---

.travis.yml
README.md

**Goal of PR**
- Auto Publish package to NPM through Travis-ci on a tag commit.

feat(travis-ci): npm auto publish

---

package.json
yarn.lock

**Goal of PR**
- Bump `rollup-plugin-node-resolve to ^5.0.1`
closes #28

chore(rollup): Bump rollup-plugin-node-resolve to ^5.0.1

---

yarn.lock

- Address some security updates in the testing suite.

chore: security updates but in test suite

---

.travis.yml

Build only on node supported versions.

chore(CI): Build only on node supported versions

---

package.json
yarn.lock

chore(security): Bump jest for security

---

.github/workflows/CI.yml
.github/workflows/publish.yml
package.json
yarn.lock

- Add github actions CI/ Publish
- Add crossenv to run scrips

chore(ci): add github actions and cross env

---

yarn.lock

security: updates

---

.github/workflows/CI.yml
.github/workflows/publish-on-tag.yml
README.md

- Add publish on tag
- Update CI build version
- Update Readme build tag.

feat: update badge and CI builds

---

yarn.lock

fix: yarnlock

---

yarn.lock

chore: Yarn upgrade

---

package.json
yarn.lock

fix(audit): major upgrade jest
